CI `all` job checks `needs` job failures
By making only the `all` test a required status check for merging to
`main` on GitHub, we can just use the `needs` of that test to determine
which CI jobs are required.

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -97,14 +97,46 @@ jobs:
         run: |
           cabal v2-run unittests
 
-  # Mandatory check on GitHub
+  # Mechanism copied from https://github.com/clash-lang/clash-compiler/
   all:
     name: All jobs finished
+    if: always()
     needs:
       - cabal
       - stack
     runs-on: ubuntu-latest
     steps:
-      - name: Void
+      - name: Checkout
+        uses: actions/checkout@v3
+
+      - name: Check dependencies for failures
         run: |
-          echo "All good"
+          # Test all dependencies for success/failure
+          set -x
+          # True if at least one dependency succeeded
+          success="${{ contains(needs.*.result, 'success') }}"
+          # True if at least one dependency failed
+          fail="${{ contains(needs.*.result, 'failure') }}"
+          set +x
+
+          # Test whether success/fail variables contain sane values
+          if [[ "${success}" != "true" && "${success}" != "false" ]]; then exit 1; fi
+          if [[ "${fail}"    != "true" && "${fail}"    != "false" ]]; then exit 1; fi
+
+          # We want to fail if one or more dependencies fail. For safety, we introduce
+          # a second check: if no dependencies succeeded something weird is going on.
+          if [[ "${fail}" == "true" || "${success}" == "false" ]]; then
+            echo "One or more dependency failed, or no dependency succeeded."
+            exit 1
+          fi
+
+      # Currently, ubuntu-latest already has it installed, but keep it around in
+      # case they ever change that
+      #
+      # - name: Install dependencies
+      #   run: |
+      #     sudo apt-get update
+      #     sudo apt-get -y install python3-yaml
+
+      - name: Check that the 'all' job depends on all other jobs
+        run: .ci/all_check.py
